---
- name: Print facts
  hosts: all
  #gather_facts: False if we uncomment variables below are not gathered
  tasks:
    - name: Print OS name
      debug:
        #var ansible_distribution
        msg: "OS name is {{ ansible_distribution }}"
    - name: Print Selinux mode
      debug:
        var: ansible_selinux.mode
    - name: Print free RAM memory
      debug:
        var: ansible_memory_mb.real.free
    - name: Print processor name
      debug:
        var: ansible_processor[2]
