---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create key pair 
      ec2_key:
        name: test-key
        region: us-east-1
      register: keyout

    #- name: print keyout
    #  debug:
    #    var: keyout

    - name: save keyout
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: ./sample.pem
      when: keyout.changed 

    - name: start an ec2 instance     
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "test-key"
        #vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
        #network_interfaces:
         # - assign_public_ip: true
        image_id: ami-0c7af5fe939f2677f
        exact_count: 1
        region: us-east-1
        tags:
          Environment: Testing 
     

     