---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on centos
      yum:
        name: chrony
        state: present
      when: ansible_distribution == 'CentOS'
    - name: Install ntp agent on ubuntu
      apt:
        name: ntp 
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
    - name: Start service on centos 
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS'
    - name: Start service on ubuntu
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'
    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS'
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Start Apache service on CentOS
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS'
    - name: Start Apache service on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'  