- name: Restart chrony service on centos
  service:
    name: chronyd
    state: restarted
  when: ansible_distribution == 'CentOS'

- name: Restart ntp service on ubuntu
  service:
    name: ntp
    state: restarted
  when: ansible_distribution == 'Ubuntu'

  
  
