#copy a file from the control instance to the managed instance
---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start service httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index file    
      copy:
        src: ../files/index.html
        dest: /var/www/html/index.html
        #owner: foo
        #group: foo {optional arguments}
        #mode: '0604'
        mode: '0644'
        backup: yes

